# Generated by Django 4.1 on 2022-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosdiarios',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gastosfijos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
