# Generated by Django 4.1 on 2022-10-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depto', '0002_alter_gastosdiarios_valor_alter_gastosfijos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantes',
            name='depto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
