# Generated by Django 4.1 on 2022-10-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depto', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=30)),
                ('rubro', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
