# Generated by Django 4.1 on 2022-10-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Depto', '0006_form_supermercado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form_Supermercado',
            new_name='Supermercado',
        ),
    ]
